09/12/2020 22:20:35 MainProcess     MainThread      logger          log_setup                 INFO     Log level set to: INFO
09/12/2020 22:20:39 MainProcess     MainThread      utils           _init_num_threads         INFO     NumExpr defaulting to 2 threads.
09/12/2020 22:20:39 MainProcess     MainThread      train           _get_images               INFO     Model A Directory: /content/Deepface-faceswap/extract_video
09/12/2020 22:20:39 MainProcess     MainThread      train           _get_images               INFO     Model B Directory: /content/Deepface-faceswap/extract_video2
09/12/2020 22:20:39 MainProcess     MainThread      train           process                   INFO     Training data directory: /content/Deepface-faceswap/Model_data_new_videos
09/12/2020 22:20:39 MainProcess     MainThread      train           _monitor                  INFO     ===================================================
09/12/2020 22:20:39 MainProcess     MainThread      train           _monitor                  INFO       Starting
09/12/2020 22:20:39 MainProcess     MainThread      train           _monitor                  INFO       Press 'ENTER' to save and quit
09/12/2020 22:20:39 MainProcess     MainThread      train           _monitor                  INFO       Press 'S' to save model weights immediately
09/12/2020 22:20:39 MainProcess     MainThread      train           _monitor                  INFO     ===================================================
09/12/2020 22:20:40 MainProcess     _training_0     train           _training                 INFO     Loading data, this may take a while...
09/12/2020 22:20:40 MainProcess     _training_0     plugin_loader   _import                   INFO     Loading Model from Original plugin...
09/12/2020 22:20:41 MainProcess     MainThread      train           _end_thread               CRITICAL Error caught! Exiting...
09/12/2020 22:20:41 MainProcess     MainThread      multithreading  join                      ERROR    Caught exception in thread: '_training_0'
09/12/2020 22:20:42 MainProcess     MainThread      launcher        execute_script            ERROR    Got Exception on main handler:
Traceback (most recent call last):
  File "/content/Deepface-faceswap/lib/cli/launcher.py", line 155, in execute_script
    process.process()
  File "/content/Deepface-faceswap/scripts/train.py", line 161, in process
    self._end_thread(thread, err)
  File "/content/Deepface-faceswap/scripts/train.py", line 201, in _end_thread
    thread.join()
  File "/content/Deepface-faceswap/lib/multithreading.py", line 121, in join
    raise thread.err[1].with_traceback(thread.err[2])
  File "/content/Deepface-faceswap/lib/multithreading.py", line 37, in run
    self._target(*self._args, **self._kwargs)
  File "/content/Deepface-faceswap/scripts/train.py", line 226, in _training
    raise err
  File "/content/Deepface-faceswap/scripts/train.py", line 214, in _training
    model = self._load_model()
  File "/content/Deepface-faceswap/scripts/train.py", line 240, in _load_model
    model = PluginLoader.get_model(self.trainer_name)(
  File "/content/Deepface-faceswap/plugins/plugin_loader.py", line 97, in get_model
    return PluginLoader._import("train.model", name, disable_logging)
  File "/content/Deepface-faceswap/plugins/plugin_loader.py", line 163, in _import
    module = import_module(mod)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/Deepface-faceswap/plugins/train/model/original.py", line 10, in <module>
    from ._base import ModelBase, logger
  File "/content/Deepface-faceswap/plugins/train/model/_base.py", line 19, in <module>
    from keras.utils import get_custom_objects, multi_gpu_model
ImportError: cannot import name 'multi_gpu_model'
09/12/2020 22:20:42 MainProcess     MainThread      launcher        execute_script            CRITICAL An unexpected crash has occurred. Crash report written to '/content/Deepface-faceswap/crash_report.2020.09.12.222041875211.log'. You MUST provide this file if seeking assistance. Please verify you are running the latest version of faceswap before reporting
